import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { motion } from 'framer-motion';
import {
  CheckCircleIcon, TimerIcon, ChartBarIcon, RobotIcon, FireIcon, CalendarBlank,
  Trophy, LightningIcon, ArrowRightIcon, StarIcon,
} from '@phosphor-icons/react';
import PublicNavbar from '../components/layout/PublicNavbar';
import { APP_CONFIG } from '../config/app.config';
import { SEO_CONFIG } from '../config/seo.config';

/* ─── animation helpers ─── */
const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.45, delay },
});

/* ─── section header component ─── */
function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <span style={{
      background: 'color-mix(in srgb, var(--color-accent) 12%, transparent)',
      border: '1px solid color-mix(in srgb, var(--color-accent) 30%, transparent)',
      borderRadius: 99, color: 'var(--color-accent)', display: 'inline-block',
      fontSize: '0.75rem', fontWeight: 600, letterSpacing: '0.06em',
      padding: '4px 14px', textTransform: 'uppercase', marginBottom: 12,
    }}>
      {children}
    </span>
  );
}

/* ─── FEATURES ─── */
const FEATURES = [
  {
    icon: <CheckCircleIcon size={28} weight="duotone" color="var(--color-accent)" />,
    title: 'Habit Tracking',
    desc: 'Build powerful streaks with a GitHub-style heatmap. Track up to 10 habits free — unlimited on Pro.',
  },
  {
    icon: <TimerIcon size={28} weight="duotone" color="var(--color-success)" />,
    title: 'Pomodoro Focus Timer',
    desc: 'Work in deep 25-minute sprints. Sessions auto-log to your subject breakdown with zero effort.',
  },
  {
    icon: <ChartBarIcon size={28} weight="duotone" color="#f59e0b" />,
    title: 'Learning Analytics',
    desc: 'See exactly how many hours you spent on DSA, React, English, or any custom subject this week.',
  },
  {
    icon: <RobotIcon size={28} weight="duotone" color="#a78bfa" />,
    title: 'AI Coach',
    badge: 'Pro',
    desc: 'Get a personalized daily review and weekly study plan generated by Claude, based on your real data.',
  },
  {
    icon: <FireIcon size={28} weight="duotone" color="#f97316" />,
    title: 'XP & Achievements',
    desc: 'Every completed habit, Pomodoro, and task earns XP. Level up and unlock achievement badges.',
  },
  {
    icon: <CalendarBlank size={28} weight="duotone" color="#22d3ee" />,
    title: 'Calendar View',
    desc: 'A monthly view that shows your activity density at a glance. Click any day to drill into details.',
  },
];

/* ─── HOW IT WORKS steps ─── */
const STEPS = [
  { step: '01', title: 'Create Your Habits', desc: 'Add habits with categories, colors, and frequency. Morning run, DSA practice, reading — whatever you track.' },
  { step: '02', title: 'Run Pomodoro Sessions', desc: 'Start a 25-minute focus session linked to a task or subject. The timer auto-logs everything when it ends.' },
  { step: '03', title: 'Review Your Progress', desc: 'Open Analytics to see your streak heatmap, subject breakdown, and focus hours. AI Coach (Pro) reviews it for you.' },
];

/* ─── TESTIMONIALS ─── */
const TESTIMONIALS = [
  { name: 'Priya S.', role: 'CS Student', text: 'I\'ve tried dozens of habit apps. HabitFlow is the first one where the timer and habits are actually connected — it makes tracking feel natural.', stars: 5 },
  { name: 'Rahul M.', role: 'Full-Stack Dev', text: 'The subject breakdown alone is worth it. I finally know I spend 60% of my study time on React and only 10% on System Design. Time to rebalance!', stars: 5 },
  { name: 'Ananya K.', role: 'UPSC Aspirant', text: 'AMOLED theme + focus mode on my phone = zero distractions. The streak counter keeps me honest every single day.', stars: 5 },
];

/* ─── STAT HIGHLIGHTS ─── */
const STATS = [
  { value: '25', unit: 'min', label: 'Pomodoro session' },
  { value: '10', unit: '+', label: 'Learning subjects' },
  { value: '∞', unit: '', label: 'Focus sessions free' },
  { value: '15', unit: '+', label: 'Achievement badges' },
];

export default function Landing() {
  const jsonLd = JSON.stringify(SEO_CONFIG.jsonLd);

  return (
    <>
      <Helmet>
        <title>{SEO_CONFIG.defaultTitle}</title>
        <meta name="description" content={SEO_CONFIG.description} />
        <meta name="keywords" content={SEO_CONFIG.keywords} />
        <meta property="og:title" content={SEO_CONFIG.defaultTitle} />
        <meta property="og:description" content={SEO_CONFIG.description} />
        <meta property="og:image" content={SEO_CONFIG.ogImage} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={APP_CONFIG.url} />
        <meta name="twitter:card" content={SEO_CONFIG.twitterCard} />
        <meta name="twitter:title" content={SEO_CONFIG.defaultTitle} />
        <meta name="twitter:description" content={SEO_CONFIG.description} />
        <meta name="twitter:image" content={SEO_CONFIG.ogImage} />
        <link rel="canonical" href={APP_CONFIG.url} />
        <script type="application/ld+json">{jsonLd}</script>
      </Helmet>

      <div style={{ background: 'var(--color-bg)', minHeight: '100dvh', overflowX: 'hidden', width: '100%' }}>
        <PublicNavbar />

        {/* ─── HERO ─── */}
        <section style={{ paddingTop: 140, paddingBottom: 100, textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          {/* Glow blob */}
          <div aria-hidden style={{
            position: 'absolute', top: '10%', left: '50%', transform: 'translateX(-50%)',
            width: 600, height: 300, borderRadius: '50%',
            background: 'radial-gradient(ellipse, color-mix(in srgb, var(--color-accent) 15%, transparent), transparent 70%)',
            pointerEvents: 'none',
          }} />

          <div style={{ maxWidth: 740, margin: '0 auto', padding: '0 24px', position: 'relative' }}>
            {/* Badge */}
            <motion.div {...fadeUp(0)} style={{ marginBottom: 20 }}>
              <SectionLabel>Free habit tracker + Pomodoro timer</SectionLabel>
            </motion.div>

            {/* Heading */}
            <motion.h1 {...fadeUp(0.05)} style={{
              color: 'var(--color-text)', fontSize: 'clamp(2.2rem, 6vw, 3.8rem)',
              fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1.12, marginBottom: 20,
            }}>
              Track habits.{' '}
              <span style={{ color: 'var(--color-accent)' }}>Master focus.</span>
              <br />Build streaks.
            </motion.h1>

            {/* Sub */}
            <motion.p {...fadeUp(0.1)} style={{
              color: 'var(--color-text-secondary)', fontSize: '1.1rem', lineHeight: 1.7,
              maxWidth: 560, margin: '0 auto 36px',
            }}>
              {APP_CONFIG.description} Built for students and developers who want to build consistent daily routines.
            </motion.p>

            {/* CTAs */}
            <motion.div {...fadeUp(0.15)} style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
              <Link to="/register" className="btn btn-primary" style={{ fontSize: '1rem', padding: '12px 28px', gap: 8 }}>
                Get Started Free <ArrowRightIcon size={18} weight="bold" />
              </Link>
              <Link to="/pricing" className="btn btn-ghost" style={{
                fontSize: '1rem', padding: '12px 24px',
                border: '1px solid var(--color-border)',
              }}>
                See Pricing
              </Link>
            </motion.div>

            {/* Social proof */}
            <motion.p {...fadeUp(0.2)} style={{ color: 'var(--color-text-muted)', fontSize: '0.8rem', marginTop: 20 }}>
              Free forever · No credit card required · Works on all devices
            </motion.p>
          </div>
        </section>

        {/* ─── STATS BAR ─── */}
        <section style={{ borderTop: '1px solid var(--color-border)', borderBottom: '1px solid var(--color-border)', padding: '40px 24px' }}>
          <div style={{ maxWidth: 960, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 32 }}>
            {STATS.map((s, i) => (
              <motion.div key={s.label} {...fadeUp(i * 0.05)} style={{ textAlign: 'center' }}>
                <div style={{ color: 'var(--color-text)', fontSize: '2rem', fontWeight: 800, fontVariantNumeric: 'tabular-nums', letterSpacing: '-0.03em' }}>
                  {s.value}<span style={{ color: 'var(--color-accent)', fontSize: '1.3rem' }}>{s.unit}</span>
                </div>
                <div style={{ color: 'var(--color-text-muted)', fontSize: '0.82rem', marginTop: 4 }}>{s.label}</div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ─── FEATURES ─── */}
        <section id="features" style={{ padding: '96px 24px' }}>
          <div style={{ maxWidth: 1080, margin: '0 auto' }}>
            <motion.div {...fadeUp()} style={{ textAlign: 'center', marginBottom: 56 }}>
              <SectionLabel>Features</SectionLabel>
              <h2 style={{ color: 'var(--color-text)', fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, letterSpacing: '-0.03em' }}>
                Everything you need to build momentum
              </h2>
              <p style={{ color: 'var(--color-text-secondary)', fontSize: '1rem', maxWidth: 520, margin: '12px auto 0' }}>
                One app for habits, focus sessions, learning analytics, and AI coaching. No tab-switching needed.
              </p>
            </motion.div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 }}>
              {FEATURES.map((f, i) => (
                <motion.div key={f.title} {...fadeUp(i * 0.07)} className="card card-hover" style={{ padding: '28px 24px' }}>
                  <div style={{ marginBottom: 14 }}>{f.icon}</div>
                  <div style={{ alignItems: 'center', display: 'flex', gap: 8, marginBottom: 8 }}>
                    <h3 style={{ color: 'var(--color-text)', fontSize: '1rem', fontWeight: 600 }}>{f.title}</h3>
                    {f.badge && (
                      <span style={{ background: 'color-mix(in srgb, var(--color-accent) 18%, transparent)', border: '1px solid color-mix(in srgb, var(--color-accent) 35%, transparent)', borderRadius: 99, color: 'var(--color-accent)', fontSize: '0.65rem', fontWeight: 700, letterSpacing: '0.08em', padding: '2px 8px', textTransform: 'uppercase' }}>
                        {f.badge}
                      </span>
                    )}
                  </div>
                  <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.875rem', lineHeight: 1.65 }}>{f.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── HOW IT WORKS ─── */}
        <section id="how-it-works" style={{ background: 'var(--color-surface)', borderTop: '1px solid var(--color-border)', borderBottom: '1px solid var(--color-border)', padding: '96px 24px' }}>
          <div style={{ maxWidth: 900, margin: '0 auto' }}>
            <motion.div {...fadeUp()} style={{ textAlign: 'center', marginBottom: 64 }}>
              <SectionLabel>How it Works</SectionLabel>
              <h2 style={{ color: 'var(--color-text)', fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, letterSpacing: '-0.03em' }}>
                Start building habits in 3 simple steps
              </h2>
            </motion.div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
              {STEPS.map((step, i) => (
                <motion.div key={step.step} {...fadeUp(i * 0.1)}
                  style={{ alignItems: 'flex-start', display: 'flex', gap: 24 }}>
                  <div style={{
                    background: 'color-mix(in srgb, var(--color-accent) 12%, transparent)',
                    border: '1px solid color-mix(in srgb, var(--color-accent) 30%, transparent)',
                    borderRadius: 12, color: 'var(--color-accent)',
                    flexShrink: 0, fontSize: '0.8rem', fontWeight: 700,
                    height: 44, lineHeight: '44px', textAlign: 'center', width: 44,
                  }}>
                    {step.step}
                  </div>
                  <div>
                    <h3 style={{ color: 'var(--color-text)', fontSize: '1.1rem', fontWeight: 600, marginBottom: 6 }}>{step.title}</h3>
                    <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.9rem', lineHeight: 1.65 }}>{step.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── APP PREVIEW MOCKUP ─── */}
        <section style={{ padding: '96px 24px', overflow: 'hidden' }}>
          <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
            <motion.div {...fadeUp()} style={{ marginBottom: 40 }}>
              <SectionLabel>App Preview</SectionLabel>
              <h2 style={{ color: 'var(--color-text)', fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, letterSpacing: '-0.03em' }}>
                A dark UI you'll actually want to open
              </h2>
            </motion.div>

            {/* Dashboard mockup card */}
            <motion.div {...fadeUp(0.1)} style={{
              background: 'var(--color-surface)', border: '1px solid var(--color-border)',
              borderRadius: 20, overflow: 'hidden',
              boxShadow: '0 0 80px color-mix(in srgb, var(--color-accent) 12%, transparent)',
            }}>
              {/* Window chrome */}
              <div style={{ alignItems: 'center', background: 'var(--color-surface-hover)', borderBottom: '1px solid var(--color-border)', display: 'flex', gap: 8, padding: '12px 16px' }}>
                {['#ef4444', '#f59e0b', '#22c55e'].map((c) => (
                  <div key={c} style={{ background: c, borderRadius: '50%', height: 12, opacity: 0.7, width: 12 }} />
                ))}
                <div style={{ background: 'var(--color-border)', borderRadius: 6, flexGrow: 1, height: 24, marginLeft: 8 }} />
              </div>

              {/* Content */}
              <div style={{ display: 'grid', gridTemplateColumns: '200px 1fr', minHeight: 340 }} className="hide-mobile">
                {/* Sidebar */}
                <div style={{ borderRight: '1px solid var(--color-border)', padding: 16 }}>
                  <div style={{ color: 'var(--color-accent)', fontWeight: 700, marginBottom: 20, padding: '0 8px' }}>HabitFlow</div>
                  {['Dashboard', 'Habits', 'Focus', 'Tasks', 'Analytics'].map((item, i) => (
                    <div key={item} style={{
                      borderRadius: 8, color: i === 0 ? 'var(--color-accent)' : 'var(--color-text-muted)',
                      background: i === 0 ? 'color-mix(in srgb, var(--color-accent) 10%, transparent)' : 'transparent',
                      fontSize: '0.8rem', fontWeight: 500, marginBottom: 2, padding: '8px 10px',
                    }}>{item}</div>
                  ))}
                </div>

                {/* Main area */}
                <div style={{ padding: 24 }}>
                  <div style={{ color: 'var(--color-text-muted)', fontSize: '0.75rem', marginBottom: 4 }}>Good morning</div>
                  <div style={{ color: 'var(--color-text)', fontSize: '1.1rem', fontWeight: 600, marginBottom: 20 }}>Today's Overview</div>

                  {/* Stat cards row */}
                  <div style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(3, 1fr)', marginBottom: 20 }}>
                    {[{ label: 'Streak', v: '🔥 18d' }, { label: 'Focus', v: '⏱ 2h 45m' }, { label: 'Habits', v: '✅ 7/9' }].map((s) => (
                      <div key={s.label} style={{ background: 'var(--color-surface-hover)', borderRadius: 10, padding: '12px 14px' }}>
                        <div style={{ color: 'var(--color-text)', fontSize: '1rem', fontWeight: 700 }}>{s.v}</div>
                        <div style={{ color: 'var(--color-text-muted)', fontSize: '0.7rem' }}>{s.label}</div>
                      </div>
                    ))}
                  </div>

                  {/* Mini habit list */}
                  {['Morning Run', 'Read 30 min', 'DSA Practice', 'Drink 2L Water'].map((h, i) => (
                    <div key={h} style={{ alignItems: 'center', borderBottom: '1px solid var(--color-border)', display: 'flex', gap: 10, padding: '8px 0' }}>
                      <div style={{ background: i < 3 ? 'var(--color-success)' : 'var(--color-surface-hover)', border: i < 3 ? 'none' : '2px solid var(--color-border)', borderRadius: '50%', height: 18, width: 18 }} />
                      <div style={{ color: i < 3 ? 'var(--color-text-secondary)' : 'var(--color-text)', fontSize: '0.8rem', textDecoration: i < 3 ? 'line-through' : 'none' }}>{h}</div>
                      {i < 3 && <div style={{ color: 'var(--color-text-muted)', fontSize: '0.7rem', marginLeft: 'auto' }}>Done</div>}
                    </div>
                  ))}
                </div>
              </div>

              {/* Mobile mockup fallback */}
              <div className="show-mobile" style={{ padding: 24 }}>
                <div style={{ color: 'var(--color-text-muted)', fontSize: '0.75rem', marginBottom: 4 }}>Good morning</div>
                <div style={{ color: 'var(--color-text)', fontSize: '1.1rem', fontWeight: 600, marginBottom: 16 }}>Today's Overview</div>
                <div style={{ display: 'grid', gap: 10, gridTemplateColumns: '1fr 1fr', marginBottom: 16 }}>
                  {[{ label: 'Streak', v: '🔥 18d' }, { label: 'Focus', v: '⏱ 2h 45m' }].map((s) => (
                    <div key={s.label} style={{ background: 'var(--color-surface-hover)', borderRadius: 10, padding: '12px' }}>
                      <div style={{ color: 'var(--color-text)', fontWeight: 700 }}>{s.v}</div>
                      <div style={{ color: 'var(--color-text-muted)', fontSize: '0.7rem' }}>{s.label}</div>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* ─── TESTIMONIALS ─── */}
        <section style={{ background: 'var(--color-surface)', borderTop: '1px solid var(--color-border)', borderBottom: '1px solid var(--color-border)', padding: '80px 24px' }}>
          <div style={{ maxWidth: 960, margin: '0 auto' }}>
            <motion.div {...fadeUp()} style={{ textAlign: 'center', marginBottom: 48 }}>
              <SectionLabel>Testimonials</SectionLabel>
              <h2 style={{ color: 'var(--color-text)', fontSize: 'clamp(1.5rem, 3vw, 2.2rem)', fontWeight: 700, letterSpacing: '-0.03em' }}>
                Loved by learners & developers
              </h2>
            </motion.div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 20 }}>
              {TESTIMONIALS.map((t, i) => (
                <motion.div key={t.name} {...fadeUp(i * 0.07)} className="card" style={{ padding: 24 }}>
                  <div style={{ display: 'flex', gap: 2, marginBottom: 12 }}>
                    {Array.from({ length: t.stars }).map((_, j) => (
                      <StarIcon key={j} size={14} weight="fill" color="#f59e0b" />
                    ))}
                  </div>
                  <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.875rem', lineHeight: 1.7, marginBottom: 16 }}>
                    "{t.text}"
                  </p>
                  <div>
                    <div style={{ color: 'var(--color-text)', fontSize: '0.875rem', fontWeight: 600 }}>{t.name}</div>
                    <div style={{ color: 'var(--color-text-muted)', fontSize: '0.78rem' }}>{t.role}</div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── PRICING TEASER ─── */}
        <section style={{ padding: '80px 24px', textAlign: 'center' }}>
          <div style={{ maxWidth: 560, margin: '0 auto' }}>
            <motion.div {...fadeUp()}>
              <SectionLabel>Pricing</SectionLabel>
              <h2 style={{ color: 'var(--color-text)', fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, letterSpacing: '-0.03em', marginBottom: 12 }}>
                Free forever. Pro for power users.
              </h2>
              <p style={{ color: 'var(--color-text-secondary)', fontSize: '1rem', lineHeight: 1.7, marginBottom: 28 }}>
                The core daily loop — habits, Pomodoro, tasks, and dashboard — is always free.
                Upgrade to Pro for unlimited everything, AI coaching, and advanced analytics.
              </p>

              <div style={{ alignItems: 'center', display: 'flex', flexWrap: 'wrap', gap: 12, justifyContent: 'center' }}>
                <Link to="/register" className="btn btn-primary" style={{ fontSize: '1rem', padding: '12px 28px' }}>
                  Start for Free
                </Link>
                <Link to="/pricing" className="btn btn-ghost" style={{ border: '1px solid var(--color-border)', fontSize: '1rem', padding: '12px 24px' }}>
                  Compare Plans <ArrowRightIcon size={16} style={{ marginLeft: 4 }} />
                </Link>
              </div>

              <div style={{ alignItems: 'center', display: 'flex', flexWrap: 'wrap', gap: 16, justifyContent: 'center', marginTop: 20 }}>
                {['Free plan available', 'Pro from ₹149/month', 'Cancel anytime'].map((perk) => (
                  <div key={perk} style={{ alignItems: 'center', color: 'var(--color-text-muted)', display: 'flex', fontSize: '0.8rem', gap: 6 }}>
                    <LightningIcon size={14} weight="fill" color="var(--color-accent)" />
                    {perk}
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </section>

        {/* ─── FINAL CTA ─── */}
        <section style={{
          background: 'color-mix(in srgb, var(--color-accent) 6%, var(--color-surface))',
          border: 'none', borderTop: '1px solid color-mix(in srgb, var(--color-accent) 20%, transparent)',
          padding: '80px 24px', textAlign: 'center',
        }}>
          <motion.div {...fadeUp()} style={{ maxWidth: 560, margin: '0 auto' }}>
            <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 20 }}>
              <Trophy size={44} weight="duotone" color="var(--color-accent)" />
            </div>
            <h2 style={{ color: 'var(--color-text)', fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, letterSpacing: '-0.03em', marginBottom: 12 }}>
              Ready to build your first streak?
            </h2>
            <p style={{ color: 'var(--color-text-secondary)', fontSize: '1rem', lineHeight: 1.7, marginBottom: 28 }}>
              Join thousands of students and developers already building better daily habits.
            </p>
            <Link to="/register" className="btn btn-primary" style={{ fontSize: '1.05rem', padding: '14px 36px' }}>
              Create Free Account
            </Link>
          </motion.div>
        </section>

        {/* ─── FOOTER ─── */}
        <footer style={{ borderTop: '1px solid var(--color-border)', padding: '40px 24px' }}>
          <div style={{ maxWidth: 1080, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
            <div style={{ color: 'var(--color-accent)', fontWeight: 700, fontSize: '1rem' }}>{APP_CONFIG.name}</div>

            <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
              {[
                { label: 'Pricing', to: '/pricing' },
                { label: 'Login', to: '/login' },
                { label: 'Register', to: '/register' },
              ].map((l) => (
                <Link key={l.label} to={l.to} style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem', textDecoration: 'none' }}>
                  {l.label}
                </Link>
              ))}
              <a href={`mailto:${APP_CONFIG.supportEmail}`} style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem', textDecoration: 'none' }}>
                Contact
              </a>
            </div>

            <div style={{ color: 'var(--color-text-muted)', fontSize: '0.78rem' }}>
              © {new Date().getFullYear()} {APP_CONFIG.name}. All rights reserved.
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
