import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { motion } from 'framer-motion';
import {
  CheckCircleIcon, TimerIcon, ChartBarIcon, RobotIcon, FireIcon, CalendarBlank,
  Trophy, LightningIcon, ArrowRightIcon, StarIcon,
} from '@phosphor-icons/react';
import PublicNavbar from '@/components/layout/PublicNavbar';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { APP_CONFIG } from '../config/app.config';
import { SEO_CONFIG } from '../config/seo.config';

/* ─── animation helpers ─── */
const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.45, delay },
});

/* ─── section header component ─── */
function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <Badge
      variant="outline"
      className="mb-3 border-primary/30 bg-primary/10 px-3.5 py-1 text-[0.75rem] font-semibold uppercase tracking-wider text-primary"
    >
      {children}
    </Badge>
  );
}

/* ─── FEATURES ─── */
const FEATURES = [
  {
    icon: CheckCircleIcon,
    iconClass: 'text-primary',
    title: 'Habit Tracking',
    desc: 'Build powerful streaks with a GitHub-style heatmap. Track up to 10 habits free — unlimited on Pro.',
  },
  {
    icon: TimerIcon,
    iconClass: 'text-green-500',
    title: 'Pomodoro Focus Timer',
    desc: 'Work in deep 25-minute sprints. Sessions auto-log to your subject breakdown with zero effort.',
  },
  {
    icon: ChartBarIcon,
    iconClass: 'text-amber-500',
    title: 'Learning Analytics',
    desc: 'See exactly how many hours you spent on DSA, React, English, or any custom subject this week.',
  },
  {
    icon: RobotIcon,
    iconClass: 'text-violet-400',
    title: 'AI Coach',
    badge: 'Pro',
    desc: 'Get a personalized daily review and weekly study plan generated by Claude, based on your real data.',
  },
  {
    icon: FireIcon,
    iconClass: 'text-orange-500',
    title: 'XP & Achievements',
    desc: 'Every completed habit, Pomodoro, and task earns XP. Level up and unlock achievement badges.',
  },
  {
    icon: CalendarBlank,
    iconClass: 'text-cyan-400',
    title: 'Calendar View',
    desc: 'A monthly view that shows your activity density at a glance. Click any day to drill into details.',
  },
];

/* ─── HOW IT WORKS steps ─── */
const STEPS = [
  { step: '01', title: 'Create Your Habits', desc: 'Add habits with categories, colors, and frequency. Morning run, DSA practice, reading — whatever you track.' },
  { step: '02', title: 'Run Pomodoro Sessions', desc: 'Start a 25-minute focus session linked to a task or subject. The timer auto-logs everything when it ends.' },
  { step: '03', title: 'Review Your Progress', desc: 'Open Analytics to see your streak heatmap, subject breakdown, and focus hours. AI Coach (Pro) reviews it for you.' },
];

/* ─── TESTIMONIALS ─── */
const TESTIMONIALS = [
  { name: 'Priya S.', role: 'CS Student', text: 'I\'ve tried dozens of habit apps. HabitFlow is the first one where the timer and habits are actually connected — it makes tracking feel natural.', stars: 5 },
  { name: 'Rahul M.', role: 'Full-Stack Dev', text: 'The subject breakdown alone is worth it. I finally know I spend 60% of my study time on React and only 10% on System Design. Time to rebalance!', stars: 5 },
  { name: 'Ananya K.', role: 'UPSC Aspirant', text: 'AMOLED theme + focus mode on my phone = zero distractions. The streak counter keeps me honest every single day.', stars: 5 },
];

/* ─── STAT HIGHLIGHTS ─── */
const STATS = [
  { value: '25', unit: 'min', label: 'Pomodoro session' },
  { value: '10', unit: '+', label: 'Learning subjects' },
  { value: '∞', unit: '', label: 'Focus sessions free' },
  { value: '15', unit: '+', label: 'Achievement badges' },
];

export default function Landing() {
  const jsonLd = JSON.stringify(SEO_CONFIG.jsonLd);

  return (
    <>
      <Helmet>
        <title>{SEO_CONFIG.defaultTitle}</title>
        <meta name="description" content={SEO_CONFIG.description} />
        <meta name="keywords" content={SEO_CONFIG.keywords} />
        <meta property="og:title" content={SEO_CONFIG.defaultTitle} />
        <meta property="og:description" content={SEO_CONFIG.description} />
        <meta property="og:image" content={SEO_CONFIG.ogImage} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={APP_CONFIG.url} />
        <meta name="twitter:card" content={SEO_CONFIG.twitterCard} />
        <meta name="twitter:title" content={SEO_CONFIG.defaultTitle} />
        <meta name="twitter:description" content={SEO_CONFIG.description} />
        <meta name="twitter:image" content={SEO_CONFIG.ogImage} />
        <link rel="canonical" href={APP_CONFIG.url} />
        <script type="application/ld+json">{jsonLd}</script>
      </Helmet>

      <div className="min-h-dvh w-full overflow-x-hidden bg-background">
        <PublicNavbar />

        {/* ─── HERO ─── */}
        <section className="relative overflow-hidden pt-[140px] pb-[100px] text-center">
          <div
            aria-hidden
            className="pointer-events-none absolute top-[10%] left-1/2 h-[300px] w-[600px] max-w-full -translate-x-1/2 rounded-full bg-primary/15 blur-3xl"
          />

          <div className="relative mx-auto max-w-[740px] px-6">
            <motion.div {...fadeUp(0)} className="mb-5">
              <SectionLabel>Free habit tracker + Pomodoro timer</SectionLabel>
            </motion.div>

            <motion.h1
              {...fadeUp(0.05)}
              className="mb-5 text-[clamp(2.2rem,6vw,3.8rem)] leading-[1.12] font-extrabold tracking-tight text-foreground"
            >
              Track habits.{' '}
              <span className="text-primary">Master focus.</span>
              <br />Build streaks.
            </motion.h1>

            <motion.p
              {...fadeUp(0.1)}
              className="mx-auto mb-9 max-w-[560px] text-[1.1rem] leading-relaxed text-muted-foreground"
            >
              {APP_CONFIG.description} Built for students and developers who want to build consistent daily routines.
            </motion.p>

            <motion.div
              {...fadeUp(0.15)}
              className="flex flex-wrap items-center justify-center gap-3"
            >
              <Button size="lg" className="gap-2 px-7 text-base" asChild>
                <Link to="/register">
                  Get Started Free <ArrowRightIcon size={18} weight="bold" />
                </Link>
              </Button>
              <Button variant="outline" size="lg" className="px-6 text-base" asChild>
                <Link to="/pricing">See Pricing</Link>
              </Button>
            </motion.div>

            <motion.p
              {...fadeUp(0.2)}
              className="mt-5 text-[0.8rem] text-muted-foreground"
            >
              Free forever · No credit card required · Works on all devices
            </motion.p>
          </div>
        </section>

        {/* ─── STATS BAR ─── */}
        <section className="border-y border-border px-6 py-10">
          <div className="mx-auto grid max-w-[960px] grid-cols-[repeat(auto-fit,minmax(160px,1fr))] gap-8">
            {STATS.map((s, i) => (
              <motion.div key={s.label} {...fadeUp(i * 0.05)} className="text-center">
                <div className="text-[2rem] font-extrabold tracking-tight text-foreground tabular-nums">
                  {s.value}
                  <span className="text-[1.3rem] text-primary">{s.unit}</span>
                </div>
                <div className="mt-1 text-[0.82rem] text-muted-foreground">{s.label}</div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ─── FEATURES ─── */}
        <section id="features" className="px-6 py-24">
          <div className="mx-auto max-w-[1080px]">
            <motion.div {...fadeUp()} className="mb-14 text-center">
              <SectionLabel>Features</SectionLabel>
              <h2 className="text-[clamp(1.6rem,3vw,2.4rem)] font-bold tracking-tight text-foreground">
                Everything you need to build momentum
              </h2>
              <p className="mx-auto mt-3 max-w-[520px] text-base text-muted-foreground">
                One app for habits, focus sessions, learning analytics, and AI coaching. No tab-switching needed.
              </p>
            </motion.div>

            <div className="grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] gap-5">
              {FEATURES.map((f, i) => (
                <motion.div key={f.title} {...fadeUp(i * 0.07)}>
                  <Card
                    className={cn(
                      'h-full py-0 transition-all hover:bg-secondary hover:shadow-md hover:ring-primary/30',
                    )}
                  >
                    <CardContent className="p-7">
                      <div className="mb-3.5">
                        <f.icon size={28} weight="duotone" className={f.iconClass} />
                      </div>
                      <div className="mb-2 flex items-center gap-2">
                        <h3 className="text-base font-semibold text-foreground">{f.title}</h3>
                        {f.badge && (
                          <Badge
                            variant="outline"
                            className="border-primary/35 bg-primary/15 px-2 py-0 text-[0.65rem] font-bold uppercase tracking-wider text-primary"
                          >
                            {f.badge}
                          </Badge>
                        )}
                      </div>
                      <p className="text-[0.875rem] leading-relaxed text-muted-foreground">{f.desc}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── HOW IT WORKS ─── */}
        <section
          id="how-it-works"
          className="border-y border-border bg-card px-6 py-24"
        >
          <div className="mx-auto max-w-[900px]">
            <motion.div {...fadeUp()} className="mb-16 text-center">
              <SectionLabel>How it Works</SectionLabel>
              <h2 className="text-[clamp(1.6rem,3vw,2.4rem)] font-bold tracking-tight text-foreground">
                Start building habits in 3 simple steps
              </h2>
            </motion.div>

            <div className="flex flex-col gap-8">
              {STEPS.map((step, i) => (
                <motion.div
                  key={step.step}
                  {...fadeUp(i * 0.1)}
                  className="flex items-start gap-6"
                >
                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-primary/30 bg-primary/10 text-[0.8rem] font-bold text-primary">
                    {step.step}
                  </div>
                  <div>
                    <h3 className="mb-1.5 text-[1.1rem] font-semibold text-foreground">{step.title}</h3>
                    <p className="text-[0.9rem] leading-relaxed text-muted-foreground">{step.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── APP PREVIEW MOCKUP ─── */}
        <section className="overflow-hidden px-6 py-24">
          <div className="mx-auto max-w-[900px] text-center">
            <motion.div {...fadeUp()} className="mb-10">
              <SectionLabel>App Preview</SectionLabel>
              <h2 className="text-[clamp(1.6rem,3vw,2.4rem)] font-bold tracking-tight text-foreground">
                A dark UI you'll actually want to open
              </h2>
            </motion.div>

            <motion.div
              {...fadeUp(0.1)}
              className="overflow-hidden rounded-[20px] border border-border bg-card shadow-[0_0_80px] shadow-primary/10"
            >
              {/* Window chrome */}
              <div className="flex items-center gap-2 border-b border-border bg-secondary px-4 py-3">
                <div className="size-3 rounded-full bg-red-500 opacity-70" />
                <div className="size-3 rounded-full bg-amber-500 opacity-70" />
                <div className="size-3 rounded-full bg-green-500 opacity-70" />
                <div className="ml-2 h-6 flex-1 rounded-md bg-border" />
              </div>

              {/* Desktop mockup */}
              <div className="hide-mobile grid min-h-[340px] grid-cols-[200px_1fr]">
                <div className="border-r border-border p-4">
                  <div className="mb-5 px-2 font-bold text-primary">HabitFlow</div>
                  {['Dashboard', 'Habits', 'Focus', 'Tasks', 'Analytics'].map((item, i) => (
                    <div
                      key={item}
                      className={cn(
                        'mb-0.5 rounded-lg px-2.5 py-2 text-[0.8rem] font-medium',
                        i === 0
                          ? 'bg-primary/10 text-primary'
                          : 'text-muted-foreground',
                      )}
                    >
                      {item}
                    </div>
                  ))}
                </div>

                <div className="p-6">
                  <div className="mb-1 text-[0.75rem] text-muted-foreground">Good morning</div>
                  <div className="mb-5 text-[1.1rem] font-semibold text-foreground">Today's Overview</div>

                  <div className="mb-5 grid grid-cols-3 gap-3">
                    {[
                      { label: 'Streak', icon: <FireIcon size={14} weight="fill" className="text-orange-500" />, v: '18d' },
                      { label: 'Focus', icon: <TimerIcon size={14} weight="duotone" className="text-primary" />, v: '2h 45m' },
                      { label: 'Habits', icon: <CheckCircleIcon size={14} weight="fill" className="text-green-500" />, v: '7/9' },
                    ].map((s) => (
                      <div key={s.label} className="rounded-[10px] bg-secondary px-3.5 py-3">
                        <div className="mb-0.5 flex items-center gap-1 text-base font-bold text-foreground">
                          {s.icon}{s.v}
                        </div>
                        <div className="text-[0.7rem] text-muted-foreground">{s.label}</div>
                      </div>
                    ))}
                  </div>

                  {['Morning Run', 'Read 30 min', 'DSA Practice', 'Drink 2L Water'].map((h, i) => (
                    <div
                      key={h}
                      className="flex items-center gap-2.5 border-b border-border py-2"
                    >
                      <div
                        className={cn(
                          'size-[18px] rounded-full',
                          i < 3
                            ? 'bg-green-500'
                            : 'border-2 border-border bg-secondary',
                        )}
                      />
                      <div
                        className={cn(
                          'text-[0.8rem]',
                          i < 3
                            ? 'text-muted-foreground line-through'
                            : 'text-foreground',
                        )}
                      >
                        {h}
                      </div>
                      {i < 3 && (
                        <div className="ml-auto text-[0.7rem] text-muted-foreground">Done</div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Mobile mockup fallback */}
              <div className="show-mobile p-6">
                <div className="mb-1 text-[0.75rem] text-muted-foreground">Good morning</div>
                <div className="mb-4 text-[1.1rem] font-semibold text-foreground">Today's Overview</div>
                <div className="mb-4 grid grid-cols-2 gap-2.5">
                  {[
                    { label: 'Streak', icon: <FireIcon size={13} weight="fill" className="text-orange-500" />, v: '18d' },
                    { label: 'Focus', icon: <TimerIcon size={13} weight="duotone" className="text-primary" />, v: '2h 45m' },
                  ].map((s) => (
                    <div key={s.label} className="rounded-[10px] bg-secondary p-3">
                      <div className="mb-0.5 flex items-center gap-1 font-bold text-foreground">
                        {s.icon}{s.v}
                      </div>
                      <div className="text-[0.7rem] text-muted-foreground">{s.label}</div>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* ─── TESTIMONIALS ─── */}
        <section className="border-y border-border bg-card px-6 py-20">
          <div className="mx-auto max-w-[960px]">
            <motion.div {...fadeUp()} className="mb-12 text-center">
              <SectionLabel>Testimonials</SectionLabel>
              <h2 className="text-[clamp(1.5rem,3vw,2.2rem)] font-bold tracking-tight text-foreground">
                Loved by learners & developers
              </h2>
            </motion.div>

            <div className="grid grid-cols-[repeat(auto-fit,minmax(260px,1fr))] gap-5">
              {TESTIMONIALS.map((t, i) => (
                <motion.div key={t.name} {...fadeUp(i * 0.07)}>
                  <Card className="h-full py-0">
                    <CardContent className="p-6">
                      <div className="mb-3 flex gap-0.5">
                        {Array.from({ length: t.stars }).map((_, j) => (
                          <StarIcon key={j} size={14} weight="fill" className="text-amber-500" />
                        ))}
                      </div>
                      <p className="mb-4 text-[0.875rem] leading-relaxed text-muted-foreground">
                        &ldquo;{t.text}&rdquo;
                      </p>
                      <div>
                        <div className="text-[0.875rem] font-semibold text-foreground">{t.name}</div>
                        <div className="text-[0.78rem] text-muted-foreground">{t.role}</div>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── PRICING TEASER ─── */}
        <section className="px-6 py-20 text-center">
          <div className="mx-auto max-w-[560px]">
            <motion.div {...fadeUp()}>
              <SectionLabel>Pricing</SectionLabel>
              <h2 className="mb-3 text-[clamp(1.6rem,3vw,2.4rem)] font-bold tracking-tight text-foreground">
                Free forever. Pro for power users.
              </h2>
              <p className="mb-7 text-base leading-relaxed text-muted-foreground">
                The core daily loop — habits, Pomodoro, tasks, and dashboard — is always free.
                Upgrade to Pro for unlimited everything, AI coaching, and advanced analytics.
              </p>

              <div className="flex flex-wrap items-center justify-center gap-3">
                <Button size="lg" className="px-7 text-base" asChild>
                  <Link to="/register">Start for Free</Link>
                </Button>
                <Button variant="outline" size="lg" className="gap-1.5 px-6 text-base" asChild>
                  <Link to="/pricing">
                    Compare Plans <ArrowRightIcon size={16} />
                  </Link>
                </Button>
              </div>

              <div className="mt-5 flex flex-wrap items-center justify-center gap-4">
                {['Free plan available', 'Pro from ₹149/month', 'Cancel anytime'].map((perk) => (
                  <div
                    key={perk}
                    className="flex items-center gap-1.5 text-[0.8rem] text-muted-foreground"
                  >
                    <LightningIcon size={14} weight="fill" className="text-primary" />
                    {perk}
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </section>

        {/* ─── FINAL CTA ─── */}
        <section className="border-t border-primary/20 bg-primary/5 px-6 py-20 text-center">
          <motion.div {...fadeUp()} className="mx-auto max-w-[560px]">
            <div className="mb-5 flex justify-center">
              <Trophy size={44} weight="duotone" className="text-primary" />
            </div>
            <h2 className="mb-3 text-[clamp(1.6rem,3vw,2.4rem)] font-bold tracking-tight text-foreground">
              Ready to build your first streak?
            </h2>
            <p className="mb-7 text-base leading-relaxed text-muted-foreground">
              Join thousands of students and developers already building better daily habits.
            </p>
            <Button size="lg" className="px-9 text-[1.05rem]" asChild>
              <Link to="/register">Create Free Account</Link>
            </Button>
          </motion.div>
        </section>

        {/* ─── FOOTER ─── */}
        <footer className="border-t border-border px-6 py-10">
          <div className="mx-auto flex max-w-[1080px] flex-wrap items-center justify-between gap-4">
            <div className="text-base font-bold text-primary">{APP_CONFIG.name}</div>

            <div className="flex flex-wrap gap-5">
              {[
                { label: 'Pricing', to: '/pricing' },
                { label: 'Login', to: '/login' },
                { label: 'Register', to: '/register' },
              ].map((l) => (
                <Link
                  key={l.label}
                  to={l.to}
                  className="text-[0.85rem] text-muted-foreground no-underline transition-colors hover:text-foreground"
                >
                  {l.label}
                </Link>
              ))}
              <a
                href={`mailto:${APP_CONFIG.supportEmail}`}
                className="text-[0.85rem] text-muted-foreground no-underline transition-colors hover:text-foreground"
              >
                Contact
              </a>
            </div>

            <div className="text-[0.78rem] text-muted-foreground">
              © {new Date().getFullYear()} {APP_CONFIG.name}. All rights reserved.
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
